### ISSUE TITLE
Algoa Bay Forecast model: Update make-forcings MatLab step to allow for restart file

### ISSUE THREAD

**Issue by zachsa** [SAEON/somisana#2]
Looking at the output of the Github actions workflow here: https://github.com/SAEON/somisana/runs/6964888710?check_suite_focus=true#step:3:40, it seems likely to me that the rst_filename  will never exist at the path that it is currently expected.

Please can you confirm this @mattcarr03. Should this be looking in the tmp directory?

**Comment by mattcarr03** [comment]
So during the model run the rst_filename is created in the scratch directory which is the "work directory". It is then moved into the forcing directory during the achieving step, line 66 
`      mv -f ${SCRATCHDIR}/rst.nc${ENDF} ${FORECASTDIR}/rst_${TIME}.nc${ENDF}
`
 in the script https://github.com/SAEON/somisana/blob/next/models/algoa-bay-forecast/toolkit/run-model/archive_croco.bash.

This was the old setup so it is possible for rst_filename to be moved where fits in best with the new workflow, possibly a folder that is not overwritten as rst_filename needs to be passed from one day to the next. The the path to look for rst_filename needs to be changed accordingly.

**Comment by zachsa** [comment]
In the old setup the same directory was reused. So for our current setup, I think it's better that the current run look for a restart file in yesterdays directory, and move it to todays forcing directory. To this end:

- There is now a step that moves the rst file generated yesterday to the current working directory (that fails silently if yesterdays run doesn't exist): https://github.com/SAEON/somisana/blob/next/.github/workflows/run_algoa-bay-forecast.yml#L263
- Then that file path is echoed into the `.env` for the matlab run
- And the matlab script restart_file_path has been updated to use that value
