### ISSUE TITLE
[Algoa Bay Forecast] Update avg.nc temporal average parameter

### ISSUE THREAD

**Issue by zachsa** [SAEON/somisana#8]
Hi @mattcarr03,

Following on from the meeting with Jenny, please can you update the `run_croco.bash` script with the correct parameter. I think it's just a matter of updating this line - https://github.com/SAEON/somisana/blob/next/models/algoa-bay-forecast/croco/run-model/run_croco.bash#L11.

When you do this, include `resolves #8` in your commit message so that the commit is linked to this thread.

**Comment by mattcarr03** [comment]
I have updated the frequency of the avg.nc file from saving every 6 hours to saving every 1 hour. 

Also you mentioned it was  https://github.com/SAEON/somisana/blob/next/models/algoa-bay-forecast/croco/run-model/run_croco.bash#L11.

I will commit it with a few other changes made
