### ISSUE TITLE
[Algoa Bay Forecast] Clean up "run_croco.bash"

### ISSUE THREAD

**Issue by zachsa** [SAEON/somisana#9]
Following on from #8, the [run_croco.bash](https://github.com/SAEON/somisana/blob/next/models/algoa-bay-forecast/croco/run-model/run_croco.bash#L11) script needs to be cleaned up. For example:

- [ ]  Currently the model is outputting a separate nc file for sea surface temperature - but it shouldn't do this, since the main avg file is the same resolution. The surface level dataset is therefore not required as model output
- [ ] Remove unused / commented code, etc

**Comment by mattcarr03** [comment]
I have updated the setup not to output a separate avg_surf.nc file. There is actually an option to not produce the surface file which is specified in the croco_frcst.in file. (https://github.com/SAEON/somisana/blob/stable/models/algoa-bay-forecast/croco/run-model/croco_frcst.in). Line 140. 

The F "flag" should be enough not to produce the file (https://croco-ocean.gitlabpages.inria.fr/croco_doc/tutos/tutos.08.run.html#edit-croco-in). I think this is easiest and then cleaning the run_croco.bash will follow
